### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by ANF-Studios**
Made it look fancy and pretty.

### CODE REVIEW

**Comment by lucasstarsz** [comment]
I like this idea.

**Comment by lucasstarsz** [comment]
I do think this is a much better format than the original lack-thereof of a real README page.
On that, I think I'll confirm this--and then make a few tweaks to it.

**Comment by spidertyler2005** [comment]
That looks fantastic. Lucas you gotta merge this right away.

**Comment by ANF-Studios** [comment]
Haha, thanks @spidertyler2005. Can't wait for this to merge :grin:

**Comment by ANF-Studios** [comment]
Thank you for merging it @lucasstarsz

**Pull request merged**
